on: push

name: CI

jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test-ci
  build:
    name: build and push docker image
    needs: test
    #if: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release*' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: steveozo/snapshot-frontend
          tags: ${{ steps.vars.outputs.short_ref }}-${GITHUB_RUN_NUMBER}
